[package]
name = "omni-daemon"
version = "0.1.0"
edition.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
publish = false

[lints]
workspace = true

[dependencies]
wisp = { path = "../wisp" }
omni-ipc = { path = "../omni-ipc" }
omni-clipboard = { path = "../omni-clipboard" }
wayland-client.workspace = true
wayland-protocols = { workspace = true, features = ["staging"] }
wayland-protocols-wlr = { workspace = true, features = ["client"] }
cosmic-text.workspace = true
tiny-skia.workspace = true
libc.workspace = true
memmap2.workspace = true
tracing.workspace = true
wayland-scanner.workspace = true
wayland-backend = "0.3"
