[workspace]
resolver = "2"
members = [
    "crates/wisp",
    "crates/wisp-components",
    "crates/omni-core",
    "crates/omni-search",
    "crates/omni-app-launcher",
    "crates/omni-daemon",
    "crates/omni-calculator",
    "crates/omni-ipc",
]

[package]
name = "omni"
version = "0.2.0"
edition.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
jemallocator.workspace = true
wayland-client.workspace = true
wayland-cursor.workspace = true
wayland-protocols-wlr = { workspace = true, features = ["client"] }
wayland-protocols.workspace = true
xkbcommon.workspace = true
cosmic-text.workspace = true
libc.workspace = true
memmap2.workspace = true
serde.workspace = true
toml.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
tiny-skia.workspace = true
omni-core = { path = "crates/omni-core" }
wisp = { path = "crates/wisp" }
wisp-components = { path = "crates/wisp-components" }
omni-app-launcher = { path = "crates/omni-app-launcher" }
omni-daemon = { path = "crates/omni-daemon" }
omni-ipc = { path = "crates/omni-ipc" }
omni-calculator = { path = "crates/omni-calculator" }
omni-search = { path = "crates/omni-search" }

[workspace.package]
publish = false
edition = "2024"
authors = ["Hyntix <dev@hyntix.com>"]
homepage = "https://github.com/HyntixHQ/omni"
repository = "https://github.com/HyntixHQ/omni"
license = "GPL-3.0"

[workspace.dependencies]
anyhow = "1"
jemallocator = "0.5.4"
wayland-client = "0.31"
wayland-cursor = "0.31"
wayland-protocols = "0.32"
wayland-protocols-wlr = { version = "0.3", features = ["client"] }
xkbcommon = "0.8"
cosmic-text = "0.12"
tiny-skia = "0.12"
resvg = "0.47"
usvg = "0.47"
image = { version = "0.25", default-features = false, features = ["png"] }
libc = "0.2"
memmap2 = "0.9"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
toml = "0.8"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["fmt", "env-filter"] }
fuzzy-matcher = "0.3"
wayland-scanner = "0.31"

[profile.release]
lto = true
codegen-units = 1
strip = "symbols"

[workspace.lints.clippy]
style = { level = "allow", priority = -1 }
todo = "deny"
dbg_macro = "deny"
too_many_arguments = "allow"
