[package]
name = "omni-calculator"
version = "0.1.0"
edition.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
tiny-skia.workspace = true
cosmic-text.workspace = true
wisp = { path = "../wisp" }
evalexpr = "13.1.0"
wisp-components = { version = "0.1.0", path = "../wisp-components" }
